### ISSUE TITLE
Create Kovan Faucet UI

### ISSUE THREAD

**Issue by pynchmeister** [zapproject/zap-ethereum-api#102]
We have the smart contract code in this repo here for a faucet: https://github.com/zapproject/zap-ethereum-api/blob/master/contracts/token/Faucet.sol

We want to wrap this with web3-react(https://github.com/NoahZinsmeister/web3-react) or an even simpler web3 library so we can have a faucet online accessible to any developer wanting to play with ZAP.

**Comment by superposition** [comment]
@adammmanka check this out
